spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:6565/ozcelikcoffeeshop
spring.datasource.username=postgres
spring.datasource.password=mert123
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.main.banner-mode=off

server.port=8080

# Maksimum dosya boyutunu 10 MB olarak ayarl?yoruz
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB









